FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.sln ./
COPY Space.Api/*.csproj Space.Api/
COPY Space.Application/*.csproj Space.Application/
COPY Space.Infrastructure/*.csproj Space.Infrastructure/
COPY Space.Domain/*.csproj Space.Domain/

RUN dotnet restore

COPY . .

WORKDIR /app/Space.Api
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5000
EXPOSE 5001

ENTRYPOINT ["dotnet", "Space.Api.dll"]