// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Space.Infrastructure.Database;

#nullable disable

namespace Space.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SpaceDbContext))]
    partial class SpaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.Geolocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GeolocationTypeId")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<int>("MeteoriteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GeolocationTypeId");

                    b.HasIndex("MeteoriteId")
                        .IsUnique();

                    b.ToTable("Geolocations");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.GeolocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("GeolocationTypes");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.Meteorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Fall")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Mass")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("NameTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecClassId")
                        .HasColumnType("integer");

                    b.Property<string>("RegionDistrictRaw")
                        .HasColumnType("text");

                    b.Property<string>("RegionGeoZoneRaw")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NameTypeId");

                    b.HasIndex("RecClassId");

                    b.ToTable("Meteorites");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.NameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("NameTypes");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.RecClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RecClasses");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.Geolocation", b =>
                {
                    b.HasOne("Space.Infrastructure.Domain.Entities.GeolocationType", "GeolocationType")
                        .WithMany("GeoLocations")
                        .HasForeignKey("GeolocationTypeId");

                    b.HasOne("Space.Infrastructure.Domain.Entities.Meteorite", "Meteorite")
                        .WithOne("GeoLocation")
                        .HasForeignKey("Space.Infrastructure.Domain.Entities.Geolocation", "MeteoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeolocationType");

                    b.Navigation("Meteorite");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.Meteorite", b =>
                {
                    b.HasOne("Space.Infrastructure.Domain.Entities.NameType", "NameType")
                        .WithMany("Meteorites")
                        .HasForeignKey("NameTypeId");

                    b.HasOne("Space.Infrastructure.Domain.Entities.RecClass", "RecClass")
                        .WithMany("Meteorites")
                        .HasForeignKey("RecClassId");

                    b.Navigation("NameType");

                    b.Navigation("RecClass");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.GeolocationType", b =>
                {
                    b.Navigation("GeoLocations");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.Meteorite", b =>
                {
                    b.Navigation("GeoLocation");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.NameType", b =>
                {
                    b.Navigation("Meteorites");
                });

            modelBuilder.Entity("Space.Infrastructure.Domain.Entities.RecClass", b =>
                {
                    b.Navigation("Meteorites");
                });
#pragma warning restore 612, 618
        }
    }
}
